services:
  - type: web
    name: draft-random-socket
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:socket
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: CLIENT_URL
        fromService:
          type: web
          name: draft-random-web
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: draft-random-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_SOCKET_URL
        fromService:
          type: web
          name: draft-random-socket
          envVarKey: RENDER_EXTERNAL_URL
